name: agentic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - openai==1.14.3
    - anthropic==0.25.0
    - langchain==0.1.14
    - langchain-openai==0.1.1
    - crewai==0.28.8
    - python-dotenv==1.0.0  
    - fastapi==0.110.0
    - uvicorn[standard]==0.29.0
    - pydantic==2.6.4
    - tenacity==8.2.3
    - tiktoken==0.6.0
    - redis==5.0.3